-- Initial production schema for a fresh PostgreSQL database.
-- Existing expand migrations remain idempotent and run after this file.

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  display_name TEXT NOT NULL,
  role TEXT NOT NULL,
  language TEXT NOT NULL,
  permission_codes JSONB NOT NULL,
  available_usdc DOUBLE PRECISION NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  senior_tester_id TEXT,
  disabled_at BIGINT,
  disabled_by TEXT,
  manager_user_id TEXT,
  permission_level TEXT NOT NULL DEFAULT 'Standard',
  failed_login_count INTEGER NOT NULL DEFAULT 0,
  locked_until BIGINT,
  password_changed_at BIGINT,
  last_login_at BIGINT,
  must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
  data_version INTEGER NOT NULL DEFAULT 1,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS rounds (
  id TEXT PRIMARY KEY,
  market_id TEXT NOT NULL,
  symbol TEXT NOT NULL,
  event_id TEXT,
  market_slug TEXT,
  event_slug TEXT,
  condition_id TEXT,
  series_slug TEXT,
  up_token_id TEXT,
  down_token_id TEXT,
  title TEXT,
  resolution_source TEXT,
  start_at BIGINT NOT NULL,
  end_at BIGINT NOT NULL,
  price_to_beat DOUBLE PRECISION NOT NULL,
  price_to_beat_source TEXT,
  price_to_beat_captured_at BIGINT,
  status TEXT NOT NULL,
  poll_count INTEGER NOT NULL,
  poll_start_at BIGINT,
  last_poll_at BIGINT,
  closing_spot_price DOUBLE PRECISION,
  settled_side TEXT,
  settlement_price DOUBLE PRECISION,
  settlement_ts BIGINT,
  redeem_start_ts BIGINT,
  redeem_finish_ts BIGINT,
  manual_reason TEXT,
  accepting_orders BOOLEAN,
  closing_price_source TEXT,
  settlement_source TEXT,
  polymarket_settlement_price DOUBLE PRECISION,
  polymarket_settlement_status TEXT,
  polymarket_open_price DOUBLE PRECISION,
  polymarket_close_price DOUBLE PRECISION,
  polymarket_open_price_source TEXT,
  polymarket_close_price_source TEXT,
  settlement_received_at BIGINT,
  redeem_scheduled_at BIGINT,
  binance_open_price DOUBLE PRECISION,
  binance_close_price DOUBLE PRECISION,
  data_version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS order_book_snapshots (
  ref TEXT PRIMARY KEY,
  snapshot_id TEXT NOT NULL,
  snapshot_ts BIGINT NOT NULL,
  best_bid DOUBLE PRECISION NOT NULL,
  best_ask DOUBLE PRECISION NOT NULL,
  mid_price DOUBLE PRECISION NOT NULL,
  snapshot JSONB NOT NULL,
  created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  trace_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  round_id TEXT NOT NULL,
  symbol TEXT NOT NULL,
  market_id TEXT NOT NULL,
  order_kind TEXT,
  time_in_force TEXT,
  limit_price DOUBLE PRECISION,
  lifecycle_status TEXT,
  result_type TEXT,
  token_id TEXT,
  book_key TEXT,
  book_hash TEXT,
  requested_amount_usdc DOUBLE PRECISION,
  requested_qty DOUBLE PRECISION,
  frozen_usdc DOUBLE PRECISION,
  frozen_qty DOUBLE PRECISION,
  fills JSONB,
  estimated_fee DOUBLE PRECISION,
  actual_fee DOUBLE PRECISION,
  fee_breakdown JSONB,
  fee_currency TEXT,
  source_latency_ms DOUBLE PRECISION,
  market_slug TEXT,
  order_book_snapshot_ref TEXT,
  order_book_snapshot JSONB,
  action TEXT NOT NULL,
  side TEXT NOT NULL,
  status TEXT NOT NULL,
  notional_usdc DOUBLE PRECISION NOT NULL,
  expected_qty DOUBLE PRECISION NOT NULL,
  filled_qty DOUBLE PRECISION NOT NULL,
  unfilled_qty DOUBLE PRECISION NOT NULL,
  avg_fill_price DOUBLE PRECISION,
  best_bid DOUBLE PRECISION NOT NULL,
  best_ask DOUBLE PRECISION NOT NULL,
  mid_price DOUBLE PRECISION NOT NULL,
  book_snapshot_ts BIGINT NOT NULL,
  partial_filled BOOLEAN NOT NULL,
  slippage_bps DOUBLE PRECISION,
  match_latency_ms DOUBLE PRECISION NOT NULL,
  book_acquire_latency_ms DOUBLE PRECISION,
  local_match_latency_ms DOUBLE PRECISION,
  persist_latency_ms DOUBLE PRECISION,
  total_order_latency_ms DOUBLE PRECISION,
  failure_reason TEXT,
  client_send_ts BIGINT,
  server_recv_ts BIGINT NOT NULL,
  server_publish_ts BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  data_version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS order_lifecycle_logs (
  id TEXT PRIMARY KEY,
  buy_order_id TEXT UNIQUE NOT NULL,
  trace_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  tester_id TEXT NOT NULL,
  round_id TEXT NOT NULL,
  symbol TEXT NOT NULL,
  asset_class TEXT NOT NULL,
  market_id TEXT NOT NULL,
  market_slug TEXT,
  direction TEXT NOT NULL,
  order_timestamp_ms BIGINT NOT NULL,
  entry_token_price DOUBLE PRECISION,
  btc_trade_price DOUBLE PRECISION,
  btc_open_price_to_beat DOUBLE PRECISION,
  delta_btc DOUBLE PRECISION,
  volume_token_qty DOUBLE PRECISION NOT NULL,
  remaining_token_qty DOUBLE PRECISION NOT NULL,
  closed_token_qty DOUBLE PRECISION NOT NULL,
  position_notional DOUBLE PRECISION NOT NULL,
  exit_type TEXT,
  exit_token_price DOUBLE PRECISION,
  exit_notional DOUBLE PRECISION NOT NULL,
  settlement_result TEXT,
  order_book_snapshot_ref TEXT,
  actual_fill_price DOUBLE PRECISION,
  slippage_bps DOUBLE PRECISION,
  match_latency_ms DOUBLE PRECISION NOT NULL,
  settlement_time_ms BIGINT,
  settlement_direction TEXT,
  entry_fee DOUBLE PRECISION,
  exit_fee DOUBLE PRECISION,
  fee_currency TEXT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  data_version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS positions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  round_id TEXT NOT NULL,
  side TEXT NOT NULL,
  qty DOUBLE PRECISION NOT NULL,
  locked_qty DOUBLE PRECISION,
  average_entry DOUBLE PRECISION NOT NULL,
  notional_spent DOUBLE PRECISION NOT NULL,
  current_mark DOUBLE PRECISION NOT NULL,
  current_bid DOUBLE PRECISION,
  current_ask DOUBLE PRECISION,
  current_mid DOUBLE PRECISION,
  current_value DOUBLE PRECISION,
  source_latency_ms DOUBLE PRECISION,
  unrealized_pnl DOUBLE PRECISION NOT NULL,
  realized_pnl DOUBLE PRECISION NOT NULL,
  entry_fee_usdc DOUBLE PRECISION,
  exit_fee_usdc DOUBLE PRECISION,
  total_fee_usdc DOUBLE PRECISION,
  cost_basis_usdc DOUBLE PRECISION,
  mark_pnl_usdc DOUBLE PRECISION,
  executable_pnl_usdc DOUBLE PRECISION,
  data_version INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL,
  opened_at BIGINT NOT NULL,
  closed_at BIGINT,
  settlement_result TEXT
);

CREATE TABLE IF NOT EXISTS audit_events (
  event_id TEXT PRIMARY KEY,
  trace_id TEXT NOT NULL,
  category TEXT NOT NULL,
  action_type TEXT NOT NULL,
  action_status TEXT NOT NULL,
  user_id TEXT,
  role TEXT,
  page_name TEXT NOT NULL,
  module_name TEXT NOT NULL,
  symbol TEXT,
  round_id TEXT,
  result_code TEXT NOT NULL,
  result_message TEXT NOT NULL,
  client_send_ts BIGINT,
  server_recv_ts BIGINT NOT NULL,
  engine_start_ts BIGINT,
  engine_finish_ts BIGINT,
  server_publish_ts BIGINT NOT NULL,
  backend_latency_ms DOUBLE PRECISION NOT NULL,
  frontend_latency_ms DOUBLE PRECISION,
  details JSONB,
  data_version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS behavior_action_logs (
  log_id TEXT PRIMARY KEY,
  timestamp_ms BIGINT NOT NULL,
  asset_class TEXT NOT NULL,
  action_type TEXT NOT NULL,
  action_status TEXT NOT NULL,
  round_id TEXT,
  direction TEXT,
  entry_odds DOUBLE PRECISION,
  delta_clob DOUBLE PRECISION NOT NULL,
  volume_clob DOUBLE PRECISION NOT NULL,
  position_notional DOUBLE PRECISION,
  exit_type TEXT,
  exit_odds DOUBLE PRECISION,
  settlement_result TEXT,
  tester_id_anon TEXT NOT NULL,
  trace_id TEXT,
  order_id TEXT,
  market_id TEXT,
  market_slug TEXT,
  round_status TEXT,
  countdown_ms BIGINT,
  binance_spot_price DOUBLE PRECISION NOT NULL,
  binance_1m_last_close DOUBLE PRECISION NOT NULL,
  binance_5m_last_close DOUBLE PRECISION NOT NULL,
  binance_1d_last_close DOUBLE PRECISION NOT NULL,
  chainlink_price DOUBLE PRECISION NOT NULL,
  price_to_beat DOUBLE PRECISION NOT NULL,
  up_price DOUBLE PRECISION NOT NULL,
  down_price DOUBLE PRECISION NOT NULL,
  up_book_top5 JSONB NOT NULL,
  down_book_top5 JSONB NOT NULL,
  recent_trades_top20 JSONB NOT NULL,
  book_snapshot_entry JSONB NOT NULL,
  actual_fill_price DOUBLE PRECISION,
  slippage_bps DOUBLE PRECISION,
  partial_filled BOOLEAN,
  unfilled_qty DOUBLE PRECISION,
  execution_latency_ms DOUBLE PRECISION,
  settlement_direction TEXT,
  settlement_time_ms BIGINT,
  gamma_poll_count INTEGER,
  redeem_finish_time_ms BIGINT,
  source_states JSONB NOT NULL,
  strategy_cluster_label TEXT,
  market_regime_label TEXT,
  quality_grade TEXT,
  context_json JSONB,
  data_version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS export_audit_logs (
  export_id TEXT PRIMARY KEY,
  actor_user_id TEXT NOT NULL,
  actor_role TEXT NOT NULL,
  export_type TEXT NOT NULL,
  format TEXT NOT NULL,
  scope JSONB NOT NULL,
  record_count INTEGER NOT NULL,
  filtered_d_grade_count INTEGER NOT NULL,
  missing_quality_count INTEGER NOT NULL,
  file_sha256 TEXT NOT NULL,
  created_at_ms BIGINT NOT NULL,
  details JSONB
);

CREATE INDEX IF NOT EXISTS idx_users_senior_tester ON users(senior_tester_id);
CREATE INDEX IF NOT EXISTS idx_users_manager_user ON users(manager_user_id);
CREATE INDEX IF NOT EXISTS idx_rounds_start_at ON rounds(start_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_book_snapshots_ts ON order_book_snapshots(snapshot_ts DESC);
CREATE INDEX IF NOT EXISTS idx_orders_user_created ON orders(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_lifecycle_user_time ON order_lifecycle_logs(user_id, order_timestamp_ms DESC);
CREATE INDEX IF NOT EXISTS idx_positions_user_opened ON positions(user_id, opened_at DESC);
CREATE INDEX IF NOT EXISTS idx_positions_user_status ON positions(user_id, status);
CREATE INDEX IF NOT EXISTS idx_positions_round_side ON positions(round_id, side);
CREATE INDEX IF NOT EXISTS idx_audit_events_user_recv ON audit_events(user_id, server_recv_ts DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_round_recv ON audit_events(round_id, server_recv_ts DESC);
CREATE INDEX IF NOT EXISTS idx_behavior_logs_timestamp ON behavior_action_logs(timestamp_ms DESC);
CREATE INDEX IF NOT EXISTS idx_behavior_logs_user_round ON behavior_action_logs(tester_id_anon, round_id, timestamp_ms DESC);
CREATE INDEX IF NOT EXISTS idx_export_audit_logs_actor_created ON export_audit_logs(actor_user_id, created_at_ms DESC);
